# Generated by Django 2.0.7 on 2018-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrador',
            fields=[
                ('idRegistrador', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('observacion', models.TextField()),
            ],
        ),
    ]
