# Generated by Django 2.0.7 on 2018-07-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitacion', '0003_auto_20180705_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fkTipo',
            field=models.ForeignKey(on_delete=None, to='Habitacion.Tipo_habitacion'),
        ),
    ]
