# Generated by Django 2.0.7 on 2018-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habitacion', '0004_auto_20180705_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='fkTipo',
            field=models.ForeignKey(on_delete=None, to='Habitacion.Tipo_habitacion'),
        ),
    ]
