# Generated by Django 2.0.7 on 2018-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCLiente', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('idNacionalidad', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200)),
                ('nacionalidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='fkNacionalidad',
            field=models.ForeignKey(on_delete=None, to='Cliente.Nacionalidad'),
        ),
    ]
